language: python
dist: xenial
python: "3.8"

stages:
  - lint
  - release

before_install:
  - PROJECT_DIR=$(pwd)/compyle
  - pip install --upgrade pip
  - pip install poetry

install:
  - poetry config virtualenvs.create false
  - poetry install --no-root --no-interaction --no-ansi --without dev

jobs:
  include:
    - stage: lint
      name: "Pylama"
      script:
        - poetry run pylama

    - stage: lint
      name: "Bandit"
      script:
        - poetry run bandit -r $PROJECT_DIR

    - stage: release
      name: "Release"
      if: branch = main AND type = push AND NOT commit_message =~ /^chore\(release\):/
      skip_cleanup: true
      script:
        - poetry run semantic-release publish
