language: python
dist: xenial
python: "3.10-dev"

cache:
  pip: true

stages:
  - lint

before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  # - PROJECT_DIR=$(pwd)
  - which poetry
  - poetry --version
  - poetry config virtualenvs.create false
  - poetry install --no-root --no-interaction

jobs:
  include:
    - stage: lint
      name: "Pylama"
      script:
        - poetry run pylama
    
    - stage: lint
      name: "Bandit"
      script:
        - poetry run bandit -r $PROJECT_DIR
