[tool.poetry]
name = "twitch-tube"
version = "0.1.0-alpha.1"
description = ""

authors = [
    "amaurylrd <amaurylrd@users.noreply.github.com>",
    "ThomasAbreuDias <ThomasAbreuDias@users.noreply.github.com>"
]
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "~3.10"
python-dotenv = "^0.21.0"
requests = "2.28.1"
djangorestframework = "^3.14"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
pylama = "^8.4.1"
pylint = "^2.15.5"
isort = "^5.10.1"


[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.isort]
exclude = '''
(
    /(
        \.git
        |\.tox
        |migrations
    )/
)
'''
include = '\.pyi?$'
line-length = 120

[tool.black]
line-length = 120