name: Release


jobs:
  release:
    needs: [lint, bandit]
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' && !contains(github.event.head_commit.message, 'chore(release):')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install Poetry
        run: pip install poetry

      - name: Install project dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --no-interaction --no-ansi --without dev

    git config user.name github-actions
    git config user.email github-actions@github.com
    
      - name: Publish release
        run: poetry run semantic-release publish


        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}