name: Run renovate
description: Run self-hosted renovate to update proetry dependencies

inputs:
  renovate-token:
    description: The Renovate token to use
    default: ${{ github.token }}

runs:
  using: composite
  steps:
  - run: git config --global core.autocrlf false
    shell: bash

  - name: Run self hosted renovate
    uses: renovatebot/github-action@v38.1.11
    env:
      RENOVATE_REPOSITORIES: ${{ github.repository }}
      RENOVATE_ONBOARDING: "false"
      RENOVATE_PLATFORM_COMMIT: "true"
    with:
      token: ${{ inputs.renovate-token }}
      configurationFile: .github/actions/renovate/renovate-config.json.js

  # ajouter les nouvelles deps dans le commit
  # - run: |
  #     git add poetry.lock
  #     git commit -m "chore(deps): update dependencies"
  #     git push
  #   shell: bash

  # - name: Use renovate
  #   uses: renovatebot/github-action@v38.1.11
  #   with:
  #     token: ${{ inputs.renovate-token }}
  #     renovate-image: ${{ inputs.renovate-image }}
  #     renovate-version: ${{ inputs.renovate-version }}
  #     configurationFile: .github/actions/renovate/renovate-config.json.js

      # https://docs.renovatebot.com/self-hosted-configuration/#dryrun
      # username: 'renovate-release',
      # TODO dire config file config.js
      # todo rajouter un poetry lock et ajouter se fichier dans le commit
      # https://docs.renovatebot.com/self-hosted-configuration/#lockfilemaintenance
