name: Run renovate
description: Run Renovate package to update proetry dependencies

# TODO dire config file config.js

inputs:
  renovate-version:
    description: The Renovate Action version to use
    default: "38.1.11"
  renovate-token:
    description: The Renovate token to use
    default: ${{ github.token }}
  renovate-image:
    description: The Renovate Docker image name to use
    default: ghcr.io/renovatebot/renovate

runs:
  using: composite
  steps:
  - run: git config --global core.autocrlf false
    shell: bash
  - name: Use renovate ${{ inputs.renovate-version }}
    uses: renovatebot/github-action@v${{ inputs.renovate-version }}
    with:
      token: ${{ inputs.renovate-token }}
      renovate-image: ${{ inputs.renovate-image }}
      dry-run: --dry-run lookup
      configurationFile: .github/actions/renovate/renovate-config.json.js

      # https://docs.renovatebot.com/self-hosted-configuration/#dryrun
      # username: 'renovate-release',
