name: Run Renovate
description: Run Renovate package to update proetry dependencies

# TODO dire config file config.js

inputs:
  renovate-version:
    description: ""
    default: "38.1.11"
  renovate-token:
    description: ""
    default: ${{ github.token }}
  renovate-image:
    description: ""
    default: myproxyhub.domain.com/renovate/renovate

runs:
  using: composite
  steps:
  - name: Self-hosted Renovate ${{ inputs.renovate-version }}
    uses: renovatebot/github-action@v${{ inputs.renovate-version }}
    with:
      token: ${{ inputs.renovate-token }}
      renovate-image: ${{ inputs.renovate-image }}
      base-dir: ${{ github.workspace }}
