name: Run renovate
description: Run self-hosted renovate to update proetry dependencies

inputs:
  renovate-token:
    description: The Renovate token to use
    default: ${{ github.token }}
  renovate-image:
    description: The Renovate Docker image name to use
    default: ghcr.io/renovatebot/renovate
  renovate-version:
    description: The Renovate Docker image version to use
    default: latest

runs:
  using: composite
  steps:
  - run: git config --global core.autocrlf false
    shell: bash

  # fork this repo https://gitlab.com/renovate-bot/renovate-runner qui est sur Gitlab et moi sur GitHub



  - name: Checkout renovate-runner
    uses: actions/checkout@v2
    with:
      repository: renovate-bot/renovate-runner
      ref: v1.0.0
      path: renovate-runner
      # sur gitlab
      # repository: https://gitlab.com/renovate-bot/renovate-runner.git
      # ref: v1.0.0
      # path: renovate-runner


  - run: |
      cd renovate-runner
      npm install
    shell: bash

  - run: |
      cd renovate-runner
      node index.js --token ${{ inputs.renovate-token }} --config-file ../renovate-config.json.js
    shell: bash

  - run: |
      git config --global user.name "Renovate Bot"
      git config --global user.email "
      git add .
      git commit -m "chore(deps): update dependencies"
      git push
    shell: bash

  # - name: Use renovate
  #   uses: renovatebot/github-action@v38.1.11
  #   with:
  #     token: ${{ inputs.renovate-token }}
  #     renovate-image: ${{ inputs.renovate-image }}
  #     renovate-version: ${{ inputs.renovate-version }}
  #     configurationFile: .github/actions/renovate/renovate-config.json.js

      # https://docs.renovatebot.com/self-hosted-configuration/#dryrun
      # username: 'renovate-release',
      # TODO dire config file config.js
      # todo rajouter un poetry lock et ajouter se fichier dans le commit
      # https://docs.renovatebot.com/self-hosted-configuration/#lockfilemaintenance
