name: Run renovate
description: Run Renovate package to update proetry dependencies

inputs:
  renovate-token:
    description: The Renovate token to use
    default: ${{ github.token }}
  # renovate-image:
  #   description: The Renovate Docker image name to use
  #   default: ghcr.io/renovatebot/renovate

runs:
  using: composite
  steps:
  - run: git config --global core.autocrlf false
    shell: bash
  - name: Use renovate
    uses: renovatebot/github-action@v38.1.11
    with:
      token: ${{ inputs.renovate-token }}
      # renovate-image: ${{ inputs.renovate-image }}
      useSlim: true
      # dry-run: --dry-run lookup
      configurationFile: .github/actions/renovate/renovate-config.json.js

      # https://docs.renovatebot.com/self-hosted-configuration/#dryrun
      # username: 'renovate-release',
      # TODO dire config file config.js
      # todo rajouter un poetry lock et ajouter se fichier dans le commit
      # https://docs.renovatebot.com/self-hosted-configuration/#lockfilemaintenance
