name: Run python semantic release
description: ""

inputs:
  github-token:
    description: "GitHub API token to publish GitHub releases"
    default: ${{ github.token }}

runs:
  using: composite
  steps:
  - run: |
      git config user.name "semantic-release"
      git config user.email "semantic-release@github-actions[bot].com"
    shell: bash
  - run: |
      poetry run semantic-release changelog --post
      poetry run semantic-release version -v DEBUG
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.github-token }}
