name: Python CI

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'
  
jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ./.github/actions/cache

  quality:
    name: Quality
    needs: [dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ./.github/actions/pylama
      # - uses: ./.github/actions/bandit
  